In [1]:
import cdd
import numpy as np

vcdd = np.array([[1.0, 0.0, 0.0,0.0,0.0],[1.0, 1.0, 1.0, 1.0, 1.0]])

# points
# 0 0 0 0
# 1 1 1 1
# square on plane : z=1



In [2]:
mat = cdd.Matrix(vcdd, number_type='float')
mat.rep_type = cdd.RepType.GENERATOR
P = cdd.Polyhedron(mat)
H = P.get_inequalities()
V = P.get_generators()
newV = np.array(V)
EQs = np.array(H)
print (EQs)
print (newV)

[[ 1. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0. -1.  0.  1.  0.]
 [ 0. -1.  0.  0.  1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# let's interpret the inequalities:

# A = 
#  1 0  0 0
# -1 0  0 0
#  1 -1 0 0
# 1  0 -1 0
# 1  0 0  -1


# B = [1 0 0 0 0]

# 1  0  0 0  * [x y z w] <= 1
# -1 0  0 0  * [x y z w] <= 0
# 1 -1  0 0  * [x y z w] <= 0
# 1  0 -1 0  * [x y z w] <= 0
# 1  0  0 -1 * [x y z w] <= 0

#  x <= 1
#  x >= 0
#  x - y <= 0
#  x - z <= 0
#  x - w <= 0


# --------------------------
# the exact constraints:
# 1  -1
# -1 1
# 1  0  -1
# -1 0  1
# 1  0  0 -1
#-1  0  0  1
#
#
#
#