In [1]:
import cdd
import numpy as np

vcdd = np.array([[1.0, 1.0,0.0,1.0],[1.0, 0.0,2.0,1.0], [1.0, 0.0,0.0,1.0], [1.0, 1.0,2.0,1.0]])

# points
#  1 0 1
#  0 2 1
#  0 0 1
#  1 2 1
# square on plane : z=1



In [ ]:
neqsA = np.array([[0.0, -1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0,0.0,-1.0], [0.0,0.0,1.0]])
neqsB = np.array([0.0, 0.0, 2.0, 1.0, -1.0, 1.0])


#  0 -1 0  * [x y z] <= 0
# -1  0 0  * [x y z] <= 0
#  0  1 0  * [x y z] <= 2
#  1  0 0  * [x y z] <= 1
#  0  0 -1 * [x y z] <= -1
#  0  0 1  * [x y z] <= 1


# Which is equivalent to ...
#  y >= 0
#  x >= 0
#  y <= 2
#  x <= 1
#  z >= 1
#  z <= 1


def compute_polytope_vertices(A, b):
    """
    Compute the vertices of a polytope given in halfspace representation by
    :math:`A x \\leq b`.
    Parameters
    ----------
    A : array, shape=(m, k)
        Matrix of halfspace representation.
    b : array, shape=(m,)
        Vector of halfspace representation.
    Returns
    -------
    vertices : list of arrays
        List of polytope vertices.
    """
    b = b.reshape((b.shape[0], 1))
    mat = cdd.Matrix(np.hstack([b, -A]), number_type='float')
    mat.rep_type = cdd.RepType.INEQUALITY
    P = cdd.Polyhedron(mat)
    g = P.get_generators()
    V = np.array(g)
    vertices = []
    for i in range(V.shape[0]):
        if V[i, 0] != 1:  # 1 = vertex, 0 = ray
            raise Exception("Polyhedron is not a polytope")
        elif i not in g.lin_set:
            vertices.append(V[i, 1:])
    return vertices


print (compute_polytope_vertices(neqsA, neqsB))

In [2]:
mat = cdd.Matrix(vcdd, number_type='float')
mat.rep_type = cdd.RepType.GENERATOR
P = cdd.Polyhedron(mat)
H = P.get_inequalities()
V = P.get_generators()
newV = np.array(V)
EQs = np.array(H)
print (EQs)
print (newV)

[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 2.  0. -1.  0.]
 [ 1. -1.  0.  0.]
 [-1.  0.  0.  1.]]
[[1. 1. 0. 1.]
 [1. 0. 2. 1.]
 [1. 0. 0. 1.]
 [1. 1. 2. 1.]]


In [ ]:
# let's interpret the inequalities:

# A = 
# 0   -1  0
# -1  0   0
# 0   1   0
# 1   0   0
# 0   0   -1


# B = [0 0 2 1 -1]

# 0   -1  0  * [x y z] <= 0
# -1  0   0  * [x y z] <= 0
# 0   1   0  * [x y z] <= 2
# 1   0   0  * [x y z] <= 1
# 0   0   -1 * [x y z] <= -1

# y >= 0
# x >= 0
# y <= 2
# x <= 1
# z >= 1