In [1]:
import pyparma
from pyparma.utils.representations import gen_from_line, ex_from_line,fractionize

import numpy as np
from fractions import Fraction

In [7]:
vcdd = np.array([[1.0, 1.0,0.0,1.0],[1.0, 0.0,2.0,1.0], [1.0, 0.0,0.0,1.0], [1.0, 1.0,2.0,1.0]])
mat = cdd.Matrix(vcdd.tolist(), number_type='float')
mat.rep_type = cdd.RepType.GENERATOR
mat.canonicalize()
print (mat)

ppl_poly = pyparma.Polyhedron(vrep=mat)

V-representation
begin
 4 4 real
  1  1  0  1
  1  0  2  1
  1  0  0  1
  1  1  2  1
end


AttributeError: 'tuple' object has no attribute 'squeeze'

In [4]:
import cdd

H-representation
begin
 3 3 rational
 0 1 0
 0 0 1
 1 -1 0
end


In [12]:
A = np.array([[1, 0, 0],
              [1, 1, 0],
              [1, 0, 1]])

mat = cdd.Matrix(A.tolist(), number_type='fraction')
mat.rep_type = cdd.RepType.GENERATOR
cdd_poly = cdd.Polyhedron(mat)

ineq = np.array(cdd_poly.get_inequalities())
print (ineq)

ppl_poly = pyparma.Polyhedron(hrep=ineq)

[[ 1 -1 -1]
 [ 0  1  0]
 [ 0  0  1]]


In [17]:
A = np.array([[0, 1, 0],
              [0, 0, 1],
              [1, -1, 0]])

mat = cdd.Matrix(A.tolist(), number_type='fraction')
mat.rep_type = cdd.RepType.INEQUALITY
mat.canonicalize()
cdd_poly = cdd.Polyhedron(mat)

gen = np.array(cdd_poly.get_generators())
print (gen)
vcdd = np.array([[1, 1,0,1],[1, 0,2,1], [1, 0,0,1], [1, 1,2,1]])
print (vcdd)

ppl_poly = pyparma.Polyhedron(vrep=vcdd)

[[1 1 0]
 [1 0 0]
 [0 0 1]]
[[1 1 0 1]
 [1 0 2 1]
 [1 0 0 1]
 [1 1 2 1]]


In [18]:
Hs = ppl_poly.hrep()
print (Hs)

[[Fraction(1, 1) Fraction(0, 1) Fraction(0, 1) Fraction(-1, 1)]
 [0 1 0 0]
 [0 0 1 0]
 [Fraction(1, 1) Fraction(-1, 1) Fraction(0, 1) Fraction(0, 1)]
 [Fraction(1, 1) Fraction(0, 1) Fraction(-1, 2) Fraction(0, 1)]]
